// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611120340_ManifestArchitecture")]
    partial class ManifestArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsLegacy")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsTaxExempt")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ClientAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedStreet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("ClientAddresses");
                });

            modelBuilder.Entity("CrewPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("TruckId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("TruckId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("CrewPresets");
                });

            modelBuilder.Entity("CrewPresetUser", b =>
                {
                    b.Property<int>("CrewId")
                        .HasColumnType("integer");

                    b.Property<int>("CrewPresetId")
                        .HasColumnType("integer");

                    b.HasKey("CrewId", "CrewPresetId");

                    b.HasIndex("CrewPresetId");

                    b.ToTable("CrewPresetMembers", (string)null);
                });

            modelBuilder.Entity("Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("EventItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("PackageId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("PackageId");

                    b.ToTable("EventItems");
                });

            modelBuilder.Entity("LogisticsAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLead")
                        .HasColumnType("boolean");

                    b.Property<int>("LogisticsTripId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LogisticsTripId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("LogisticsAssignments");
                });

            modelBuilder.Entity("Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceOverride")
                        .HasColumnType("numeric");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PackageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("PackageId", "InventoryItemId")
                        .IsUnique();

                    b.ToTable("PackageItems");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("integer");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CardBrand")
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("Last4")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessedById")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatedTransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ProcessedById");

                    b.HasIndex("RelatedTransactionId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapacityCubicFeet")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<int?>("WeightLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("server.Models.Event.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BillingAddressEntryUid")
                        .HasColumnType("uuid");

                    b.Property<string>("BillingAddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingAddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("BillingCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ClientUid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeliveryAddressEntryUid")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryAddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryAddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EventEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("server.Models.Event.LogisticsPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LogisticsWorkItemId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LogisticsWorkItemId");

                    b.ToTable("LogisticsPhotos");
                });

            modelBuilder.Entity("server.Models.Event.LogisticsTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClientSignatureUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TruckId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("TruckId", "ScheduledStart", "ScheduledEnd");

                    b.ToTable("LogisticsTrips");
                });

            modelBuilder.Entity("server.Models.Event.LogisticsWorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LogisticsTripId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecificNotes")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("LogisticsTripId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("LogisticsWorkItems");
                });

            modelBuilder.Entity("server.Models.Inventory.BounceHouseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventorySubTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventorySubTypeId");

                    b.ToTable("BounceHouseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventorySubTypeId = 6,
                            Label = "Standard Castle",
                            Name = "StandardCastle"
                        },
                        new
                        {
                            Id = 2,
                            InventorySubTypeId = 6,
                            Label = "Combo (Jump & Slide)",
                            Name = "Combo"
                        },
                        new
                        {
                            Id = 3,
                            InventorySubTypeId = 6,
                            Label = "Water Slide",
                            Name = "WaterSlide"
                        },
                        new
                        {
                            Id = 4,
                            InventorySubTypeId = 6,
                            Label = "Obstacle Course",
                            Name = "ObstacleCourse"
                        },
                        new
                        {
                            Id = 5,
                            InventorySubTypeId = 6,
                            Label = "Interactive Game",
                            Name = "Interactive"
                        });
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventorySubTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventorySubTypeId");

                    b.HasIndex("InventoryTypeId");

                    b.ToTable("InventoryColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventorySubTypeId = 1,
                            Label = "Black",
                            Name = "Black",
                            SkuCode = "BLK"
                        },
                        new
                        {
                            Id = 2,
                            InventorySubTypeId = 2,
                            Label = "Black",
                            Name = "Black",
                            SkuCode = "BLK"
                        },
                        new
                        {
                            Id = 3,
                            InventorySubTypeId = 1,
                            Label = "White",
                            Name = "White",
                            SkuCode = "WHT"
                        },
                        new
                        {
                            Id = 4,
                            InventorySubTypeId = 2,
                            Label = "White",
                            Name = "White",
                            SkuCode = "WHT"
                        },
                        new
                        {
                            Id = 5,
                            InventorySubTypeId = 3,
                            Label = "Solid White",
                            Name = "SolidWhite",
                            SkuCode = "WHT"
                        },
                        new
                        {
                            Id = 6,
                            InventorySubTypeId = 3,
                            Label = "Clear Top",
                            Name = "ClearTop",
                            SkuCode = "CLR"
                        },
                        new
                        {
                            Id = 7,
                            InventorySubTypeId = 4,
                            Label = "Solid White",
                            Name = "SolidWhite",
                            SkuCode = "WHT"
                        },
                        new
                        {
                            Id = 8,
                            InventorySubTypeId = 4,
                            Label = "Clear Top",
                            Name = "ClearTop",
                            SkuCode = "CLR"
                        },
                        new
                        {
                            Id = 9,
                            InventorySubTypeId = 8,
                            Label = "Solid White",
                            Name = "SolidWhite",
                            SkuCode = "WHT"
                        },
                        new
                        {
                            Id = 10,
                            InventorySubTypeId = 8,
                            Label = "Clear Top",
                            Name = "ClearTop",
                            SkuCode = "CLR"
                        });
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("ParentItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildItemId");

                    b.HasIndex("ParentItemId", "ChildItemId")
                        .IsUnique();

                    b.ToTable("InventoryComponents");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AveragePurchaseCost")
                        .HasColumnType("numeric");

                    b.Property<int?>("BounceHouseTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("InventoryColorId")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryMaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("InventorySubTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("InventoryTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("PackageOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Variant")
                        .HasColumnType("text");

                    b.Property<decimal?>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BounceHouseTypeId");

                    b.HasIndex("InventoryColorId");

                    b.HasIndex("InventoryMaterialId");

                    b.HasIndex("InventorySubTypeId");

                    b.HasIndex("InventoryTypeId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventorySubTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventorySubTypeId");

                    b.HasIndex("InventoryTypeId");

                    b.ToTable("InventoryMaterials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventorySubTypeId = 1,
                            Label = "Plastic",
                            Name = "Plastic",
                            SkuCode = "PLT"
                        },
                        new
                        {
                            Id = 2,
                            InventorySubTypeId = 2,
                            Label = "Plastic",
                            Name = "Plastic",
                            SkuCode = "PLT"
                        },
                        new
                        {
                            Id = 3,
                            InventorySubTypeId = 1,
                            Label = "Resin",
                            Name = "Resin",
                            SkuCode = "RSN"
                        },
                        new
                        {
                            Id = 4,
                            InventorySubTypeId = 1,
                            Label = "Metal",
                            Name = "Metal",
                            SkuCode = "MTL"
                        },
                        new
                        {
                            Id = 5,
                            InventorySubTypeId = 3,
                            Label = "Standard Vinyl",
                            Name = "Vinyl",
                            SkuCode = "VNL"
                        },
                        new
                        {
                            Id = 6,
                            InventorySubTypeId = 4,
                            Label = "Standard Vinyl",
                            Name = "Vinyl",
                            SkuCode = "VNL"
                        },
                        new
                        {
                            Id = 7,
                            InventorySubTypeId = 8,
                            Label = "Standard Vinyl",
                            Name = "Vinyl",
                            SkuCode = "VNL"
                        },
                        new
                        {
                            Id = 8,
                            InventorySubTypeId = 4,
                            Label = "Sailcloth",
                            Name = "Sailcloth",
                            SkuCode = "SCL"
                        });
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePurchased")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityPurchased")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric");

                    b.Property<string>("VendorName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("InventoryPurchases");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryRetirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRetired")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("QuantityRetired")
                        .HasColumnType("integer");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("InventoryRetirements");
                });

            modelBuilder.Entity("server.Models.Inventory.InventorySubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventoryTypeId");

                    b.ToTable("InventorySubTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventoryTypeId = 1,
                            Label = "Folding",
                            Name = "Folding",
                            SkuCode = "FLD"
                        },
                        new
                        {
                            Id = 2,
                            InventoryTypeId = 2,
                            Label = "Folding",
                            Name = "Folding",
                            SkuCode = "FLD"
                        },
                        new
                        {
                            Id = 3,
                            InventoryTypeId = 3,
                            Label = "Canopy / Pop-Up",
                            Name = "Canopy",
                            SkuCode = "CNP"
                        },
                        new
                        {
                            Id = 4,
                            InventoryTypeId = 3,
                            Label = "Pole Tent",
                            Name = "Pole",
                            SkuCode = "POL"
                        },
                        new
                        {
                            Id = 8,
                            InventoryTypeId = 3,
                            Label = "Frame Tent",
                            Name = "Frame",
                            SkuCode = "FRM"
                        },
                        new
                        {
                            Id = 5,
                            InventoryTypeId = 5,
                            Label = "Mechanical Bull",
                            Name = "MechanicalBull",
                            SkuCode = "MBL"
                        },
                        new
                        {
                            Id = 6,
                            InventoryTypeId = 5,
                            Label = "Inflatable / Bounce House",
                            Name = "Inflatable",
                            SkuCode = "INF"
                        },
                        new
                        {
                            Id = 7,
                            InventoryTypeId = 4,
                            Label = "String Lights",
                            Name = "String",
                            SkuCode = "STR"
                        });
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InventoryTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Table",
                            Name = "Table",
                            SkuCode = "TAB"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Chair",
                            Name = "Chair",
                            SkuCode = "CHA"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Tent",
                            Name = "Tent",
                            SkuCode = "TNT"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Lighting",
                            Name = "Lighting",
                            SkuCode = "LGT"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Attraction",
                            Name = "Attraction",
                            SkuCode = "ATR"
                        });
                });

            modelBuilder.Entity("server.Models.TaxJurisdiction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HighRate")
                        .HasColumnType("numeric");

                    b.Property<string>("LocCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LowRate")
                        .HasColumnType("numeric");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCodePlus4")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocCode");

                    b.HasIndex("ZipCode", "City", "Address");

                    b.ToTable("TaxJurisdictions");
                });

            modelBuilder.Entity("server.Models.User.JobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("server.Models.User.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("server.Models.User.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("server.Models.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("JobTitleId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PayRate")
                        .HasColumnType("numeric");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClientAddress", b =>
                {
                    b.HasOne("Client", "Client")
                        .WithMany("ClientAddresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CrewPreset", b =>
                {
                    b.HasOne("server.Models.User.User", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("CrewPresetUser", b =>
                {
                    b.HasOne("server.Models.User.User", null)
                        .WithMany()
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrewPreset", null)
                        .WithMany()
                        .HasForeignKey("CrewPresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Discount", b =>
                {
                    b.HasOne("server.Models.Event.Event", null)
                        .WithMany("Discounts")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventItem", b =>
                {
                    b.HasOne("server.Models.Event.Event", "Event")
                        .WithMany("Items")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Inventory.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId");

                    b.HasOne("Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.Navigation("Event");

                    b.Navigation("InventoryItem");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("LogisticsAssignment", b =>
                {
                    b.HasOne("server.Models.Event.LogisticsTrip", "LogisticsTrip")
                        .WithMany("Crew")
                        .HasForeignKey("LogisticsTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LogisticsTrip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PackageItem", b =>
                {
                    b.HasOne("server.Models.Inventory.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Package", "Package")
                        .WithMany("Items")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("server.Models.User.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.User.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.HasOne("server.Models.Event.Event", "Event")
                        .WithMany("Transactions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.User.User", "ProcessedBy")
                        .WithMany()
                        .HasForeignKey("ProcessedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transaction", "RelatedTransaction")
                        .WithMany()
                        .HasForeignKey("RelatedTransactionId");

                    b.Navigation("Event");

                    b.Navigation("ProcessedBy");

                    b.Navigation("RelatedTransaction");
                });

            modelBuilder.Entity("server.Models.Event.LogisticsPhoto", b =>
                {
                    b.HasOne("server.Models.Event.LogisticsWorkItem", "LogisticsWorkItem")
                        .WithMany("Photos")
                        .HasForeignKey("LogisticsWorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogisticsWorkItem");
                });

            modelBuilder.Entity("server.Models.Event.LogisticsTrip", b =>
                {
                    b.HasOne("Truck", "Truck")
                        .WithMany("Trips")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("server.Models.Event.LogisticsWorkItem", b =>
                {
                    b.HasOne("server.Models.Event.Event", "Event")
                        .WithMany("LogisticsWorkItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("server.Models.Event.LogisticsTrip", "LogisticsTrip")
                        .WithMany("WorkItems")
                        .HasForeignKey("LogisticsTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("LogisticsTrip");
                });

            modelBuilder.Entity("server.Models.Inventory.BounceHouseType", b =>
                {
                    b.HasOne("server.Models.Inventory.InventorySubType", "InventorySubType")
                        .WithMany("BounceHouseTypes")
                        .HasForeignKey("InventorySubTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventorySubType");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryColor", b =>
                {
                    b.HasOne("server.Models.Inventory.InventorySubType", "InventorySubType")
                        .WithMany("Colors")
                        .HasForeignKey("InventorySubTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Inventory.InventoryType", null)
                        .WithMany("Colors")
                        .HasForeignKey("InventoryTypeId");

                    b.Navigation("InventorySubType");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryComponent", b =>
                {
                    b.HasOne("server.Models.Inventory.InventoryItem", "ChildItem")
                        .WithMany("ParentItems")
                        .HasForeignKey("ChildItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Models.Inventory.InventoryItem", "ParentItem")
                        .WithMany("Components")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildItem");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryItem", b =>
                {
                    b.HasOne("server.Models.Inventory.BounceHouseType", "BounceHouseType")
                        .WithMany()
                        .HasForeignKey("BounceHouseTypeId");

                    b.HasOne("server.Models.Inventory.InventoryColor", "Color")
                        .WithMany()
                        .HasForeignKey("InventoryColorId");

                    b.HasOne("server.Models.Inventory.InventoryMaterial", "Material")
                        .WithMany()
                        .HasForeignKey("InventoryMaterialId");

                    b.HasOne("server.Models.Inventory.InventorySubType", "SubType")
                        .WithMany()
                        .HasForeignKey("InventorySubTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Inventory.InventoryType", "Type")
                        .WithMany()
                        .HasForeignKey("InventoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BounceHouseType");

                    b.Navigation("Color");

                    b.Navigation("Material");

                    b.Navigation("SubType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryMaterial", b =>
                {
                    b.HasOne("server.Models.Inventory.InventorySubType", "InventorySubType")
                        .WithMany("Materials")
                        .HasForeignKey("InventorySubTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Inventory.InventoryType", null)
                        .WithMany("Materials")
                        .HasForeignKey("InventoryTypeId");

                    b.Navigation("InventorySubType");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryPurchase", b =>
                {
                    b.HasOne("server.Models.Inventory.InventoryItem", "InventoryItem")
                        .WithMany("Purchases")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryRetirement", b =>
                {
                    b.HasOne("server.Models.Inventory.InventoryItem", "InventoryItem")
                        .WithMany("Retirements")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("server.Models.Inventory.InventorySubType", b =>
                {
                    b.HasOne("server.Models.Inventory.InventoryType", "InventoryType")
                        .WithMany("SubTypes")
                        .HasForeignKey("InventoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryType");
                });

            modelBuilder.Entity("server.Models.User.User", b =>
                {
                    b.HasOne("server.Models.User.JobTitle", "JobTitle")
                        .WithMany("Users")
                        .HasForeignKey("JobTitleId");

                    b.HasOne("server.Models.User.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTitle");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.Navigation("ClientAddresses");
                });

            modelBuilder.Entity("Package", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Truck", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("server.Models.Event.Event", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Items");

                    b.Navigation("LogisticsWorkItems");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("server.Models.Event.LogisticsTrip", b =>
                {
                    b.Navigation("Crew");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("server.Models.Event.LogisticsWorkItem", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryItem", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("ParentItems");

                    b.Navigation("Purchases");

                    b.Navigation("Retirements");
                });

            modelBuilder.Entity("server.Models.Inventory.InventorySubType", b =>
                {
                    b.Navigation("BounceHouseTypes");

                    b.Navigation("Colors");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("server.Models.Inventory.InventoryType", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Materials");

                    b.Navigation("SubTypes");
                });

            modelBuilder.Entity("server.Models.User.JobTitle", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("server.Models.User.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
